version: '3'

networks:
  kanban-net:
    driver: bridge

services:
  back:
    build:
      context: ./BACK/
      dockerfile: Dockerfile
    container_name: back-kanban
    restart: always
    ports:
      - '5000:5000'
    networks:
      - kanban-net

  front:
    build:
      context: ./FRONT/
      dockerfile: Dockerfile
    container_name: front-kanban
    restart: always
    ports:
      - '3000:80'
    networks:
      - kanban-net
