version: '3'

networks:
  kanban-net:
    driver: bridge

services:
  back:
    build: ./BACK
    container_name: back-kanban
    restart: always
    ports:
      - '5000:5000'
    networks:
      - kanban-net

  front:
    build: ./FRONT
    container_name: front-kanban
    restart: always
    ports:
      - '8080:8080'
    networks:
      - kanban-net
